name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: install environment
      run: sudo apt-get install -y build-essential perl python git
    - name: init repo
      run: perl init-repository
      
